fails:Exception#exception creates new object ands sets #message to argument
fails:Exception#exception returns self when passed self as an argument
fails:Exception.exception creates new object if an argument responding to to_s is given
fails:Exception#exception returns an exception of the same class as self with the message given as argument, but without reinitializing
